source 'https://rubygems.org'
ruby '3.1.2'

gem 'rails', '~> 7.0.4'

gem 'pg', '~> 1.1'

gem 'puma', '~> 5.0'


gem 'devise'
gem 'redis'
gem 'sidekiq'
gem 'connection_pool'

group :development, :test do
  gem 'pry'
  gem 'pry-rails'
  gem 'rspec'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
